#+TITLE: Orgpx

This is a package for organizing your favorite places as Org Mode
entries. I think that showing your favorite places for a given
category in a maps applications is an awesome feature, but I would
rather organize that list of favorite places together with my other
notes in Org Mode. This package accomplishes that.

The package is a work in progress and is not really prepared to be
shared yet, use the code at your own risk.

** Installation

For now, just load manually the Elisp files in this repository.


** Dependencies

There are a few dependencies that you will need to have previously
installed. When I package this code properly they will be
automatically installed, but for now it needs to be done manually

- Org Mode, of course

- https://github.com/minad/osm


** How it works
*** Defining locations
**** Location format

A favorite place is just an Org Entry with LATITUDE and LONGITUDE
properties. Other optional fields are:
- A tag, which will be the location category (e.g., restaurant). Tags
  can be inherited from parent entries, or define in the location
  entry itself. Only one tag will be used when exporting to a gpx
  file, with children tags having priority over parent tags (behavior
  of multiple tags in a single entry undefined for now)
- Description, which is just the body of the entry, excluding children

The exported name of the favorite place will just be the heading of
the entry.

**** Locations' location

Location entries should be in the files specified by the ~orgpx-files~
variable, which should be a list of files or a function which takes no
arguments and returns a list of files.

For example, I use org-roam and add the =orgpx= tag to nodes which
contain favorite locations, and use this function:

#+begin_src emacs-lisp
(defun orgpx-org-roam-nodes-with-tags (tags)
  "Return the list of Org Roam nodes with given tags TAGS."
  (cl-remove-duplicates  ;; org-roam aliases make nodes appear more than once
   (mapcar #'org-roam-node-file
           (seq-filter
            (lambda (node)
              (seq-some (lambda (tag-name)
                          (member tag-name (org-roam-node-tags node)))
                        tags))
            (org-roam-node-list)))))

#+end_src

You could also use ~org-agenda-files~ or a function that returns all
the files in a your notes directory

*** Operating on locations
**** Exporting locations to gpx file

To export your favorite locations to a gpx file, just run
~(orgpx-export FILE)~. By gpx file, I mean a file that can be used to
import your favorite locations to OsmAnd. I don't really know the gpx
stardard, I just used the OsmAnd exports for reference.

There are a few limitations when using this to sync your favorite
locations with OsmAns:
- The saved places will just be some coordinates, not an actual
  POI. This also happens if you export a POI and immediately re-import
  it in OsmAnd, so there doesn't seem to be anything this package can
  do about it, there is no extra metadata that we can save to fix
  it. The only way to have a POI as saved place, is to save it
  directly from inside OsmAnd.
- If the saved place already existed in OsmAnd, it won't be updated
  nor duplicated on import, just ignored. I'm not sure of the exact
  rules OsmAnd follows to decide a place is the same, but if the
  coordinates are name are the same it decides it is. If you need
  other fields like the description to be updated, the only solution
  for now is deleting all your favorite places and re-imorting them
  again.

**** Viewing locations

***** With osm.el

~orgpx-open-with-osm~ will open the location at point using osm.el

***** With Google Maps

~orgpx-open-with-google~ will open the location at point with Google
Maps. It will only open the map at the given coordinates, but the
place will not be selected as an actual POI.

** Future improvements
*** [#C] Open multiple locations with osm

You can open multiple locations given by a gpx file with osm.el, but
it's likely to trigger rate limiting. I want to find out and document
how to use offline maps (see (https://github.com/minad/osm/issues/27)
for reference), and then define a functions for querying a subset of
your favorite locations using org-ql and displaying them with osm.el

*** [#C] Import favorite places from OsmAnd

A proper two-way sync is complex and not planned for now, but an
initial import from a gpx files into locations entries following the
orgpx format should be supported

*** [#D] Automate completely syncing favorite places with OsmAnd
I think fully automating it is out of the scope of this package, but
at least we could automate as much as possible and document the
possible options:
- Using OsmAnd Cloud, the only option that should be able to be
  fully automated
- Doint it manually
- Using tools like Syncthing
*** [#D] Two-way sync between orgpx and OsmAnd
*** [#E] Open location in Google Maps as POI

Right now when we open a location with Google Maps we just open the
map at the given coordinates, but if it's a named location and we want
to select it, we need to click it manually. It seems that to actually
open the place without an extra click you need the Google place id,
which can be queried in their API. To use it you need to register, and
the free tier should be enough for querying place ids on demand and
save them as Org properties when needed. I might try some time, but it
has very low priority.
